Repository Zerhadow/Day-Night, pull requests merged in 2023-03, with the labels that each got.

#4 Add files via upload
  Day & Night/Assets/Art/Models.meta
  Day & Night/Assets/Art/Models/Import.meta
  Day & Night/Assets/Art/Models/Import/Rock_cluster.fbx
  Day & Night/Assets/Art/Models/Import/Rock_cluster.fbx.meta
  Day & Night/Assets/Art/Models/Import/Training_dummy.fbx
  Day & Night/Assets/Art/Models/Import/Training_dummy.fbx.meta
  Day & Night/Assets/Art/Models/Import/Training_dummyClean.fbx
  Day & Night/Assets/Art/Models/Import/Training_dummyClean.fbx.meta
  Day & Night/Assets/Art/Models/Import/Tree_W.fbx
  Day & Night/Assets/Art/Models/Import/Tree_W.fbx.meta
  Day & Night/Assets/Art/Models/Import/Tree_cone_Wide.fbx
  Day & Night/Assets/Art/Models/Import/Tree_cone_Wide.fbx.meta
  Day & Night/Assets/Art/Models/Import/Tree_reg.fbx
  Day & Night/Assets/Art/Models/Import/Tree_reg.fbx.meta
  Day & Night/Assets/Art/Models/Import/Woodsword_broken.fbx
  Day & Night/Assets/Art/Models/Import/Woodsword_broken.fbx.meta
  Day & Night/Assets/Art/Models/Import/rock.fbx
  Day & Night/Assets/Art/Models/Import/rock.fbx.meta
  Day & Night/Assets/Art/Models/importV2.meta
  Day & Night/Assets/Art/Models/importV2/Banner.fbx
  Day & Night/Assets/Art/Models/importV2/Banner.fbx.meta
  Day & Night/Assets/Art/Models/importV2/Banner_float.fbx
  Day & Night/Assets/Art/Models/importV2/Banner_float.fbx.meta
  Day & Night/Assets/Art/Models/importV2/Banner_round.fbx
  Day & Night/Assets/Art/Models/importV2/Banner_round.fbx.meta
  Day & Night/Assets/Art/Models/importV2/Skull.fbx
  Day & Night/Assets/Art/Models/importV2/Skull.fbx.meta
  Day & Night/Assets/Art/Models/importV2/SkullWithBones.fbx
  Day & Night/Assets/Art/Models/importV2/SkullWithBones.fbx.meta
  Day & Night/Assets/Art/Models/importV2/Tree_dead.fbx
  Day & Night/Assets/Art/Models/importV2/Tree_dead.fbx.meta
  Day & Night/Assets/Art/Models/importV2/Weapon_axe_broken.fbx
  Day & Night/Assets/Art/Models/importV2/Weapon_axe_broken.fbx.meta
  Day & Night/Assets/Art/Models/importV2/bone.fbx
  Day & Night/Assets/Art/Models/importV2/bone.fbx.meta
  Day & Night/UserSettings/Layouts/default-2021.dwlt
Labels: Models

#5 Test
  Day & Night/.vsconfig
  Day & Night/Assets/Scenes/Jarod.unity
  Day & Night/Assets/Scripts/Player.meta
  Day & Night/Assets/Scripts/Player/Camera.cs
  Day & Night/Assets/Scripts/Player/Camera.cs.meta
  Day & Night/Assets/Scripts/Player/Movement.cs
  Day & Night/Assets/Scripts/Player/Movement.cs.meta
  Day & Night/Assets/Settings/URP-HighFidelity-Renderer.asset
  Day & Night/UserSettings/EditorUserSettings.asset
Labels: Programming

#9 added test map
  Day & Night/Assets/Art/Materials/New Material.mat
  Day & Night/Assets/Art/Materials/New Material.mat.meta
  Day & Night/Assets/Scenes/TestBox_Skyler.unity
  Day & Night/Assets/Scenes/TestBox_Skyler.unity.meta
  Day & Night/UserSettings/EditorUserSettings.asset
  Day & Night/UserSettings/Layouts/default-2021.dwlt
Labels: Design

#10 Pause Menu Functionality
  Day & Night/Assets/Art/Animations/PauseMenu.anim
  Day & Night/Assets/Art/Animations/PauseMenu.anim.meta
  Day & Night/Assets/Art/Animations/PauseMenu.controller
  Day & Night/Assets/Art/Animations/PauseMenu.controller.meta
  Day & Night/Assets/Art/Materials/Grass.mat
  Day & Night/Assets/Art/Materials/Grass.mat.meta
  Day & Night/Assets/Art/Materials/GrassSamp1.jpg
  Day & Night/Assets/Art/Materials/GrassSamp1.jpg.meta
  Day & Night/Assets/Art/Materials/Player.mat
  Day & Night/Assets/Art/Materials/Player.mat.meta
  Day & Night/Assets/Scenes/Julian.unity
  Day & Night/Assets/Scripts/UI/PauseMenu.cs
  Day & Night/Assets/Scripts/UI/PauseMenu.cs.meta
  Day & Night/UserSettings/EditorUserSettings.asset
  Day & Night/UserSettings/Layouts/default-2021.dwlt
Labels: UI/UX

#16 Basic Enemy Follows Player & massive script import
  Day & Night/Assets/Art/Materials/Blue.mat
  Day & Night/Assets/Art/Materials/Blue.mat.meta
  Day & Night/Assets/Art/Materials/REd.mat
  Day & Night/Assets/Art/Materials/REd.mat.meta
  Day & Night/Assets/Scenes/Julian2.meta
  Day & Night/Assets/Scenes/Julian2.unity
  Day & Night/Assets/Scenes/Julian2.unity.meta
  Day & Night/Assets/Scenes/Julian2/NavMesh-Enemy.asset
  Day & Night/Assets/Scenes/Julian2/NavMesh-Enemy.asset.meta
  Day & Night/Assets/Scenes/Julian2/NavMesh-NavMesh.asset
  Day & Night/Assets/Scenes/Julian2/NavMesh-NavMesh.asset.meta
  Day & Night/Assets/Scripts/Enemy/BasicEnemyAI.cs
  Day & Night/Assets/Scripts/Enemy/BasicEnemyAI.cs.meta
  Day & Night/Assets/Scripts/Enemy/EnemyAI.cs
  Day & Night/Assets/Scripts/Enemy/EnemyAI.cs.meta
  Day & Night/Assets/Scripts/Enemy/EnemyAIController.cs
  Day & Night/Assets/Scripts/Enemy/EnemyAIController.cs.meta
  Day & Night/Assets/Scripts/Enemy/EnemyController.cs
  Day & Night/Assets/Scripts/Enemy/EnemyController.cs.meta
  Day & Night/Assets/Scripts/Enemy/EnemyHPBar.cs
  Day & Night/Assets/Scripts/Enemy/EnemyHPBar.cs.meta
  Day & Night/Assets/Scripts/NavMeshComponents.meta
  Day & Night/Assets/Scripts/NavMeshComponents/Editor.meta
  Day & Night/Assets/Scripts/NavMeshComponents/Editor/NavMeshAssetManager.cs
  Day & Night/Assets/Scripts/NavMeshComponents/Editor/NavMeshAssetManager.cs.meta
  Day & Night/Assets/Scripts/NavMeshComponents/Editor/NavMeshComponentsEditor.asmdef
  Day & Night/Assets/Scripts/NavMeshComponents/Editor/NavMeshComponentsEditor.asmdef.meta
  Day & Night/Assets/Scripts/NavMeshComponents/Editor/NavMeshComponentsGUIUtility.cs
  Day & Night/Assets/Scripts/NavMeshComponents/Editor/NavMeshComponentsGUIUtility.cs.meta
  Day & Night/Assets/Scripts/NavMeshComponents/Editor/NavMeshLinkEditor.cs
  Day & Night/Assets/Scripts/NavMeshComponents/Editor/NavMeshLinkEditor.cs.meta
  Day & Night/Assets/Scripts/NavMeshComponents/Editor/NavMeshModifierEditor.cs
  Day & Night/Assets/Scripts/NavMeshComponents/Editor/NavMeshModifierEditor.cs.meta
  Day & Night/Assets/Scripts/NavMeshComponents/Editor/NavMeshModifierVolumeEditor.cs
  Day & Night/Assets/Scripts/NavMeshComponents/Editor/NavMeshModifierVolumeEditor.cs.meta
  Day & Night/Assets/Scripts/NavMeshComponents/Editor/NavMeshSurfaceEditor.cs
  Day & Night/Assets/Scripts/NavMeshComponents/Editor/NavMeshSurfaceEditor.cs.meta
  Day & Night/Assets/Scripts/NavMeshComponents/Scripts.meta
  Day & Night/Assets/Scripts/NavMeshComponents/Scripts/NavMeshComponents.asmdef
  Day & Night/Assets/Scripts/NavMeshComponents/Scripts/NavMeshComponents.asmdef.meta
  Day & Night/Assets/Scripts/NavMeshComponents/Scripts/NavMeshLink.cs
  Day & Night/Assets/Scripts/NavMeshComponents/Scripts/NavMeshLink.cs.meta
  Day & Night/Assets/Scripts/NavMeshComponents/Scripts/NavMeshModifier.cs
  Day & Night/Assets/Scripts/NavMeshComponents/Scripts/NavMeshModifier.cs.meta
  Day & Night/Assets/Scripts/NavMeshComponents/Scripts/NavMeshModifierVolume.cs
  Day & Night/Assets/Scripts/NavMeshComponents/Scripts/NavMeshModifierVolume.cs.meta
  Day & Night/Assets/Scripts/NavMeshComponents/Scripts/NavMeshSurface.cs
  Day & Night/Assets/Scripts/NavMeshComponents/Scripts/NavMeshSurface.cs.meta
  Day & Night/Assets/Scripts/Systems/Audio.meta
  Day & Night/Assets/Scripts/Systems/Audio/AudioFile.cs
  Day & Night/Assets/Scripts/Systems/Audio/AudioFile.cs.meta
  Day & Night/Assets/Scripts/Systems/Audio/AudioManager.cs
  Day & Night/Assets/Scripts/Systems/Audio/AudioManager.cs.meta
  Day & Night/Assets/Scripts/Systems/WaveSpawner.cs
  Day & Night/Assets/Scripts/Systems/WaveSpawner.cs.meta
  Day & Night/Assets/Scripts/UI/HUDHealth.cs
  Day & Night/Assets/Scripts/UI/HUDHealth.cs.meta
  Day & Night/ProjectSettings/TagManager.asset
  Day & Night/UserSettings/EditorUserSettings.asset
  Day & Night/UserSettings/Layouts/default-2021.dwlt
Labels: Programming

#17 Koolcrab patch 1
  Day & Night/Assets/Art/Models/ImportV5/BrokenFence.fbx
  Day & Night/Assets/Art/Models/ImportV5/Fence_broken tile.fbx
  Day & Night/Assets/Art/Models/ImportV5/Weapons/Crossbow_Bolt.fbx
  Day & Night/Assets/Art/Models/ImportV5/Weapons/Hero_Weapon_Blunderbuss.fbx
  Day & Night/Assets/Art/Models/ImportV5/Weapons/Hero_Weapon_Crossbow.fbx
  Day & Night/Assets/Art/Models/ImportV5/Weapons/Hero_Weapon_Crossbow_Empty.fbx
  Day & Night/Assets/Art/Models/ImportV5/Weapons/Hero_Weapon_Sword.fbx
  Day & Night/Assets/Art/Models/ImportV5/WoodWalkway_NoSUpp.fbx
  Day & Night/Assets/Art/Models/ImportV5/fence.fbx
  Day & Night/Assets/Art/Models/ImportV6/BIg_Box.fbx
  Day & Night/Assets/Art/Models/ImportV6/Box.fbx
  Day & Night/Assets/Art/Models/ImportV6/Gate.fbx
  Day & Night/Assets/Art/Models/ImportV6/Gate_Spikes.fbx
  Day & Night/Assets/Art/Models/ImportV6/NewBanner.fbx
  Day & Night/Assets/Art/Models/ImportV6/NewBanner_Point.fbx
  Day & Night/Assets/Art/Models/ImportV6/NewBanner_round.fbx
  Day & Night/Assets/Art/Models/ImportV6/Rocks_NewCluster.fbx
  Day & Night/Assets/Art/Models/ImportV6/Stone_Arch.fbx
  Day & Night/Assets/Art/Models/ImportV6/Stone_Stairs.fbx
  Day & Night/Assets/Art/Models/ImportV6/Wood_Barrel.fbx
  Day & Night/Assets/Art/Models/ImportV6/Wood_Corner.fbx
Labels: Models

#26 Wave System fully implemented
  Day & Night/Assets/Scenes/Julian2.unity
  Day & Night/Assets/Scripts/Systems/WaveSpawner.cs
  Day & Night/UserSettings/Layouts/default-2021.dwlt
Labels: Programming

#31 Got all colliders working. Health UI working
  Day & Night/Assets/Prefabs/Enemies/MeleeEnemy.prefab
  Day & Night/Assets/Prefabs/Player/Potion.prefab
  Day & Night/Assets/Prefabs/Player/Potion.prefab.meta
  Day & Night/Assets/Prefabs/Weapons/Fireball Caster.prefab
  Day & Night/Assets/Prefabs/Weapons/Projectiles/Bolt.prefab
  Day & Night/Assets/Scenes/Julian2.unity
  Day & Night/Assets/Scripts/Enemy/EnemyController.cs
  Day & Night/Assets/Scripts/Enemy/EnemyProjectile.cs
  Day & Night/Assets/Scripts/Player/PlayerController.cs
  Day & Night/Assets/Scripts/Systems/PotionSpawn.cs
  Day & Night/Assets/Scripts/Systems/WaveSpawner.cs
  Day & Night/Assets/Scripts/Weapons/Bolt.cs
  Day & Night/Assets/Scripts/Weapons/Fireball.cs
  Day & Night/Assets/Scripts/Weapons/FireballCaster.cs
  Day & Night/Assets/Scripts/Weapons/MeleeSwing.cs
  Day & Night/Assets/Scripts/Weapons/Pellet.cs
  Day & Night/Assets/Scripts/Weapons/Projectile.cs
  Day & Night/UserSettings/EditorUserSettings.asset
Labels: Programming
